name: CI/CD

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write      # required for OIDC
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      RUN_SONAR: false  # set to true to enable SonarCloud

    steps:
    - uses: actions/checkout@v6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Build builder image
      run: docker build --target builder -t app:builder .

    - name: Run tests
      run: docker run --rm app:builder uv sync --extra dev && uv run pytest --maxfail=1 --disable-warnings -q --cov=app --junitxml=report.xml

    - name: Build production image
      run: docker build --target production -t app:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        image-ref: python:3.12-slim-bookworm
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    - name: SonarCloud scan
      if: env.RUN_SONAR == 'true'
      uses: sonarsource/sonarqube-scan-action@v7.0.0
      with:
        projectBaseDir: .
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2.0.1

    - name: CDK bootstrap
      run: |
        cd cdk
        pip install -r requirements.txt
        cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-east-1

    - name: CDK synth
      run: cdk synth

    - name: CDK diff
      run: cdk diff

    - name: Deploy CDK
      run: cdk deploy --require-approval never
